FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src src
COPY data data
COPY artifacts artifacts
COPY mlruns mlruns

CMD ["python", "src/training/train.py"]
